### PR TITLE
TF-1487: Voice Link support for ServiceNow

### PR DESCRIPTION
**Pull request by Shankar-khati**
JIRA Link: https://growtenfold.atlassian.net/browse/TF-1487
Brief Description: Add support to push recording links for customers using the Voice Link feature. It will require that we add support to handling the property "recordingLink" in the methods responsible for creating and updating calls in the CRM integration.

I have tested these changes locally, seems to be working fine.

### CODE REVIEW

**Comment by Shankar-khati** [comment]
We need to close this PR since @Tinadim is making these changes in another PR.

**Comment by Shankar-khati** [comment]
I had a conversation with @Tinadim  and there was some confusion related to ServiceNow application changes, I thought these changes will be made by @Tinadim in his changes. But @Tinadim is creating a new ServiceNow application.  So we need these changes for voice link feature.

**Review by reisandbeans — APPROVED** [review]

**Comment by reisandbeans** [comment]
For the record, I already took care of adding this field and it's respective mapping in the new app

**Comment by Shankar-khati** [comment]
Closing this PR because it has some unwanted changes. created new for the same https://github.com/tenfold/sn_application/pull/10

**Pull request closed without merging**
